### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by bcsam** [bcsam/FinalProject2.0#29]
Leaving this as a note of times when the app crashes

**Comment by bcsam** [comment]
When sometimes clicking on profile images in the messaging activity

**Comment by bcsam** [comment]
Crashes in Compose Activity from incomingList being null

**Comment by vivfang** [comment]
crashes when returning to profile activity
android.database.StaleDataException: Attempted to access a cursor after it has been closed.

**Comment by vivfang** [comment]
Crashes when pressing back from compose activity
